PL/Models/DTO/Ciudad.cs
namespace PL.Models.DTO
{
    public class Ciudad
    {
        public int IdCiudad { get; set; }

        public string NombreCiudad { get; set; }
    }
}

PL/Models/DTO/Editorial.cs
namespace PL.Models.DTO
{
    public class Editorial
    {
        public int IdEditorial { get; set; }

        public string Nombre { get; set; }

        public List<Models.DTO.Editorial> Editoriales { get; set; }

        public Models.DTO.Ciudad Ciudad { get; set; }
    }
}

PL/Models/DTO/Libro.cs
namespace PL.Models.DTO
{
    public class Libro
    {
        public int IdLibro { get; set; }

        public string Titulo { get; set; }

        public string Autor { get; set; }

        public string Isbn { get; set; }

        public DateTime AnioPublicacion { get; set; }

        public Editorial Editorial { get; set; }
        public Ciudad Ciudad { get; set; }
        public List<Models.DTO.Libro> Libros { get; set; }
    }
}

PL/Models/ErrorViewModel.cs
namespace PL.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PL/Models/Result.cs
namespace PL.Models
{
    public class Result
    {
        public bool Success { get; set; }
        public string Message { get; set; }
        public Exception Error { get; set; }
        public object Data { get; set; }
    }
}

PL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PL.Models;
using System.Diagnostics;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PL/Controllers/LibroController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class LibroController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PL/Views/Libro/Index.cshtml
<h3>Libros</h3>

<div style="margin: 20px">
    <!-- Button trigger modal -->
    <button type="button" id="btnModal" onclick="Limpiar()" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#miModal">
        Agregar Libro
    </button>
</div>

<div class="container">
    <table id="miTabla" class="table table-striped table-responsive">
        <thead class="table table-dark">
            <tr>
                <th></th>
                <th>Titulo</th>
                <th>Autor</th>
                <th>ISBN</th>
                <th>Año Publicación</th>
                <th>Editorial</th>
                <th>Ciudad</th>
                <th></th>
            </tr>
        </thead>
        <tbody id="showLibros"></tbody>
    </table>
</div>

<!--------Modal------->
<div class="modal fade" id="miModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="textTituloModal">Agregar Libro</h5>
                <button id="closeM" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>
            <div class="modal-body">

                <div class="row justify-content-center">
                    <div class="col-7">
                        <input id="ddlIdLibro"  class="form-control" type="hidden" />
                    </div>
                </div>

                <div class="row justify-content-center">
                    <div class="col-7">
                        <label class="form-label">Titulo</label>
                        @*onkeypress="LetrasYNumeros(this,'lblTitulo')"*@
                        <input id="ddlTitulo" class="form-control" type="text" placeholder="Titulo Libro"  />
                        <label id="lblTitulo" style="color: red"></label>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-7">
                        <label class="form-label">Autor</label>
                        <input id="ddlAutor" class="form-control" type="text" placeholder="Autor" onkeypress="SoloLetras(this,'lblAutor')" />
                        <label id="lblAutor" style="color: red"></label>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-7">
                        <label class="form-label">ISBN</label>
                        <input id="ddlIsbn" class="form-control" type="text" placeholder="ISBN" onkeypress="Isbn(this, 'lblIsbn')" />
                        <label id="lblIsbn" style="color: red"></label>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-7">
                      @*  *@
                        <label class="form-label">Año de Publicacion</label>
                        <input class="form-control" type="number" value="1800" min="1600" max="2024"  id="ddlAnio" onblur="FechaPubli(this, 'lblAnio')"/>

                        <label id="lblAnio" style="color: red"></label>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-7">
                        <label class="form-label">Editorial</label>
                        <select id="ddlEditorial" class="form-select">Selecciona una Opcion</select>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="btnExit" type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                <button id="btnUpd" onclick="Update()" style="display: none" type="button" class="btn btn-success">Guardar cambios</button>
                <button id="btnAdd" onclick="Add()" style="display: none" type="button" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </div>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/LibroAjax.js" asp-append-version="true"></script>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libro" asp-action="Index">Libros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>